fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt : "https://github.com/puppetlabs/puppetlabs-apt.git"

  symlinks:
    profile_redis: "#{source_dir}"
